version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
    

  auth-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-app
    ports: 
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: "mongodb://root:examplepassword@mongodb:27017"
      CONFIG_PATH: ./config/local.yaml
      MONGO_DATABASE: auth
      JWT_SIGNING_KEY: local


volumes:
  mongodb_data: