env: "local"

storage_path: "./storage.db"

http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 30s

mongo: 
 database_user:
 database_password:
 database_name: "auth"

jwt:
 access_token_ttl: 15m
 refresh_token_ttl: 720h