env: "prod"

storage_path: "./storage.db"

http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 30s
  user: "Shabby8574"

mongo: 
 database_url:
 database_user:
 database_password:
 database_name: sessions
